repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        args: [ "--config=setup.cfg" ]
        language: python
        types: [ python ]
        always_run: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-ast
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: double-quote-string-fixer

  - repo: local
    hooks:
      - id: fmt
        name: fmt
        entry: make
        args: [ "fmt" ]
        language: system
        pass_filenames: false

  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: make
        args: [ "lint" ]
        language: system
        pass_filenames: false
